### ISSUE TITLE
your random isn't random

### ISSUE THREAD

**Issue by mkillebrew** [diversionmary/raffle_rng#5] opened 2017-08-12 17:52 UTC
time isn't random, os.urandom is
modulo bias is quite severe in odd numbers, weighting entire ranges. Even numbers, max is least likely.

**Comment by diversionmary** [comment] 2017-08-16 16:16
Thoughts on this change?

```
def get_seed():
      # This will get our random seed
      preseed = str(os.urandom(32))
      return hashlib.sha1(preseed).hexdigest()
```

**Comment by slickplaid** [comment] 2017-08-17 05:14
That change is fine and honestly it doesn't make any difference. We're just trying to make it unlikely (extremely unlikely) that the seed cannot be guessed. That time value doesn't make it easier to guess the seed. We can remove the time value if it would make you feel better.

From there, the modulus skew is negated by increasing the draw range of the initial random number as shown by the example below. 

Here is a a script that tests the modulus distribution:
```python
#!/usr/bin/python
import random
import platform
import math

slots = 10
min = 0
max = (slots * math.pow(10, 6)) - 1
iterations = 10**7
rounds = 10
a = 0


print("Testing {} rounds of {} iterations\n\n".format(rounds, iterations))
while a < rounds:
    a = a + 1
    i = 0
    prob = [0] * slots
    stats = [0] * slots
    print("Iteration {}".format(a))
    while i < iterations:
        i = i + 1
        big_result = random.randint(min, max)
        winner = big_result % slots
        stats[winner-1] = stats[winner-1] + 1
    for x in range(slots):
        prob[x] = round(float(stats[x]) / i * 100, 4)
    print("%: {}".format(prob))
    print("Wins: {}".format(stats))
    m = sum(prob) / len(prob)
    variance = sum([(xi - m)**2 for xi in prob]) / (len(prob) - 1)
    print("Variance: +/- {}%".format(round(variance, 4)))
    print("")

```

Here is the output I got:
```
Testing 10 rounds of 10000000 iterations


Iteration 1
%: [10.0098, 10.0053, 9.9999, 9.9985, 10.0035, 10.0027, 9.9945, 9.9905, 9.9994, 9.9959]
Wins: [1000978, 1000535, 999985, 999851, 1000348, 1000267, 999448, 999049, 999945, 999594]
Variance: +/- 0.0%

Iteration 2
%: [9.9969, 10.0131, 9.9906, 10.0063, 9.9995, 10.0071, 10.0075, 9.9745, 10.0149, 9.9895]
Wins: [999690, 1001311, 999064, 1000630, 999949, 1000708, 1000754, 997451, 1001494, 998949]
Variance: +/- 0.0002%

Iteration 3
%: [9.9991, 10.0038, 10.0071, 10.011, 9.985, 9.9988, 9.9862, 10.0176, 10.0106, 9.9808]
Wins: [999907, 1000377, 1000711, 1001101, 998499, 999881, 998622, 1001762, 1001064, 998076]
Variance: +/- 0.0002%

Iteration 4
%: [9.995, 10.0012, 10.0049, 10.0078, 9.9991, 10.0004, 10.0059, 9.9877, 10.0105, 9.9875]
Wins: [999497, 1000122, 1000494, 1000781, 999905, 1000038, 1000594, 998771, 1001053, 998745]
Variance: +/- 0.0001%

Iteration 5
%: [9.9966, 10.0069, 9.9806, 9.9809, 10.0228, 9.9976, 9.9861, 10.007, 10.001, 10.0205]
Wins: [999663, 1000691, 998062, 998090, 1002284, 999755, 998605, 1000704, 1000101, 1002045]
Variance: +/- 0.0002%

Iteration 6
%: [10.0051, 9.9763, 9.9913, 10.01, 10.0177, 10.0048, 9.9988, 9.9956, 10.006, 9.9944]
Wins: [1000508, 997630, 999129, 1001005, 1001770, 1000480, 999878, 999562, 1000603, 999435]
Variance: +/- 0.0001%

Iteration 7
%: [10.0002, 9.9901, 10.0081, 10.0093, 9.9956, 9.9957, 10.0182, 9.9902, 9.9901, 10.0026]
Wins: [1000019, 999013, 1000806, 1000927, 999560, 999574, 1001822, 999017, 999005, 1000257]
Variance: +/- 0.0001%

Iteration 8
%: [10.0025, 10.0049, 10.0072, 10.0092, 9.9879, 10.0153, 10.0022, 9.9947, 9.9877, 9.9883]
Wins: [1000247, 1000492, 1000719, 1000920, 998795, 1001534, 1000218, 999474, 998773, 998828]
Variance: +/- 0.0001%

Iteration 9
%: [9.9983, 10.0052, 10.0016, 9.9889, 10.0037, 10.0104, 10.0125, 9.9691, 10.0098, 10.0006]
Wins: [999834, 1000520, 1000158, 998888, 1000366, 1001040, 1001251, 996907, 1000980, 1000056]
Variance: +/- 0.0002%

Iteration 10
%: [10.0214, 9.9979, 9.984, 10.0102, 9.9983, 10.0137, 9.9826, 10.0001, 10.0009, 9.9909]
Wins: [1002136, 999794, 998405, 1001017, 999826, 1001365, 998259, 1000014, 1000092, 999092]
Variance: +/- 0.0002%

```

Can you explain better where the issue is? The time function is only involved in the seed generation, not in the actually drawing of the random number and from what I can see even iterating over the results millions of times, has a very uniform distribution of winners.

**Comment by jjmerri** [comment] 2017-08-17 18:35
There is no modulo bias. The max is calculated as:
max = (eventual_max * math.pow(10, 6)) - 1
where eventual_max is the number of slots

This ensures:
(max % num_slots) + 1 = 0

The definition of modulo bias is:
(max % num_slots) + 1 **!=** 0

**Comment by diversionmary** [comment] 2017-08-17 20:24
@mkillebrew I'm going to close this issue, but please reach out if you aren't satisfied.

**Closed by diversionmary** 2017-08-17 20:24 UTC
